(* Generated by ocp-build *)
let package = "tzscan-config"
let version = "0.1"
let authors = [
   ]
let copyright = ""
let license = ""
let description = ""
let api_host = ""
let api_port = ""
let database = "betanet"
let commit = "f9f246ac"
let date = "2019-07-18 11:35"
let en_date = "2019-07-18 11:35"
let has_pgocaml = true
let requires = [
  ]
