version: '1.0.{build}'

image:
  - Visual Studio 2019

services:
  - postgresql101

environment:
  APPVEYOR_RDP_PASSWORD: V3RY_str0ng_P455WoRD

configuration: Release

platform:
  - x64
  - x86


build: off

branches:
  only:
    - master

for:
  - matrix:
      only:
        - image: Visual Studio 2019
    clone_folder: 'C:\projects\tezos_stats'
    cache:
      - 'C:\Users\appveyor\.esy'
      - 'C:\Users\appveyor\AppData\Roaming\npm\esy'
    install:
      - 'npm install -g esy@0.5.8'
    build_script:
      - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
      - esy @appveyor install
      - esy @appveyor build echo $PGPASSWORD
      - esy @appveyor build

clone_depth: 5

test: off

deploy: off
