// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Caml_splice_call = require("bs-platform/lib/js/caml_splice_call.js");

function div(param, param$1) {
  return Caml_splice_call.spliceApply(React.createElement, [
              "div",
              param !== undefined ? Caml_option.valFromOption(param) : undefined,
              param$1
            ]);
}

function p(param, param$1) {
  return Caml_splice_call.spliceApply(React.createElement, [
              "p",
              param !== undefined ? Caml_option.valFromOption(param) : undefined,
              param$1
            ]);
}

function button(param, param$1) {
  return Caml_splice_call.spliceApply(React.createElement, [
              "button",
              param !== undefined ? Caml_option.valFromOption(param) : undefined,
              param$1
            ]);
}

function table(param, param$1) {
  return Caml_splice_call.spliceApply(React.createElement, [
              "table",
              param !== undefined ? Caml_option.valFromOption(param) : undefined,
              param$1
            ]);
}

function thead(param, param$1) {
  return Caml_splice_call.spliceApply(React.createElement, [
              "thead",
              param !== undefined ? Caml_option.valFromOption(param) : undefined,
              param$1
            ]);
}

function tbody(param, param$1) {
  return Caml_splice_call.spliceApply(React.createElement, [
              "tbody",
              param !== undefined ? Caml_option.valFromOption(param) : undefined,
              param$1
            ]);
}

function tr(param, param$1) {
  return Caml_splice_call.spliceApply(React.createElement, [
              "tr",
              param !== undefined ? Caml_option.valFromOption(param) : undefined,
              param$1
            ]);
}

function th(param, param$1) {
  return Caml_splice_call.spliceApply(React.createElement, [
              "th",
              param !== undefined ? Caml_option.valFromOption(param) : undefined,
              param$1
            ]);
}

function td(param, param$1) {
  return Caml_splice_call.spliceApply(React.createElement, [
              "td",
              param !== undefined ? Caml_option.valFromOption(param) : undefined,
              param$1
            ]);
}

function img(param, param$1) {
  return Caml_splice_call.spliceApply(React.createElement, [
              "img",
              param !== undefined ? Caml_option.valFromOption(param) : undefined,
              param$1
            ]);
}

exports.div = div;
exports.p = p;
exports.button = button;
exports.table = table;
exports.thead = thead;
exports.tbody = tbody;
exports.tr = tr;
exports.th = th;
exports.td = td;
exports.img = img;
/* react Not a pure module */
