// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Shortcut = require("./shortcut.bs.js");

function make(prop) {
  return Shortcut.table(undefined, /* array */[
              Shortcut.thead(undefined, /* array */[Shortcut.tr(undefined, $$Array.map((function (s) {
                                return Shortcut.th(undefined, /* array */[s]);
                              }), prop.headers))]),
              Shortcut.tbody(undefined, $$Array.map((function (row) {
                          return Shortcut.tr(undefined, $$Array.map((function (s) {
                                            return Shortcut.th(undefined, /* array */[s]);
                                          }), row));
                        }), prop.body))
            ]);
}

exports.make = make;
/* Shortcut Not a pure module */
